### ISSUE TITLE
Add missing releases for the latest versions 

### ISSUE THREAD

**Issue by LonerDan** [PainKiller3/android_kernel_xiaomi_sdm845#1]
Can you please add releases of the versions after the v4.4? I have precompiled kernel v5.3 and I want to compile additional drivers but I don't know which commit corresponds to that release.

**Comment by PainKiller3** [comment]
I think you is checking the wrong branch
Plox check ten branch thanks

**Comment by LonerDan** [comment]
No, I am checking the 'ten' branch. The latest code is there but I am talking about the releases.
![Screenshot_20200703-212646](https://user-images.githubusercontent.com/11718484/86494088-2dc59180-bd74-11ea-8a56-b31aa0c97db4.jpg)

**Comment by PainKiller3** [comment]
Well I stopped uploading on GitHub but u can found it here 
https://www.pling.com/p/1347883/

**Comment by LonerDan** [comment]
I found those, but they are only compiled binary form. I would like the corresponding source code they were made from (as is with the old GitHub releases).
![Screenshot_20200703-213702](https://user-images.githubusercontent.com/11718484/86494438-729df800-bd75-11ea-8203-4c3ccaf685b3.jpg)

**Comment by PainKiller3** [comment]
If u r talking about changelog then it has been posted on my channel and 5.x source code is already pushed

**Comment by LonerDan** [comment]
No, I mean for example, which GitHub commit corresponds to v5.3?
Edit: Like there was before, when you were releasing it on Github. There was a release tag (the version number you gave it) and commit that indicated the version of source code from which it was made.
![86494438-729df800-bd75-11ea-8203-4c3ccaf685b3](https://user-images.githubusercontent.com/11718484/86497119-9b77ba80-bd80-11ea-938e-ead09c431493.jpg)

**Comment by PainKiller3** [comment]
Not gonna do that anymore
